import React from 'react';

export default function TableList({
  title,
  description,
  count,
  items,
  inputValue,
  onInputChange,
  onAdd,
  placeholder = '',
  addLabel = 'Add',
  renderRow,
}) {
  return (
    <div className="rounded-3xl border border-black/8 bg-white/95 p-5 shadow-[0_16px_40px_rgba(0,0,0,0.05)]">
      <div className="mb-4 flex items-start justify-between gap-4 border-b border-black/8 pb-4">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full bg-black px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-white">
            <span className="h-3.5 w-3.5" />
            {title}
          </div>
          {description ? <p className="mt-3 max-w-2xl text-sm text-black/60">{description}</p> : null}
        </div>
        <div className="rounded-2xl bg-black px-4 py-2 text-sm font-semibold text-white">{count} items</div>
      </div>

      <form onSubmit={onAdd} className="mb-4 flex flex-col gap-3 sm:flex-row">
        <input
          value={inputValue}
          onChange={(e) => onInputChange(e.target.value)}
          placeholder={placeholder}
          className="flex-1 rounded-2xl border border-black/10 px-4 py-3 text-sm outline-none"
        />
        <button type="submit" className="rounded-2xl bg-black px-4 py-3 text-sm font-semibold text-white">{addLabel}</button>
      </form>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-xs text-gray-500">
              {/* header generated by renderRow when given, otherwise assume default keys */}
              <th className="px-3 py-2">ID</th>
              <th className="px-3 py-2">Name</th>
              <th className="px-3 py-2 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((it) => renderRow ? renderRow(it) : (
              <tr key={it.id} className="border-t">
                <td className="px-3 py-2 font-mono text-sm text-gray-700">{it.id}</td>
                <td className="px-3 py-2">{it.name}</td>
                <td className="px-3 py-2 text-right">—</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
